apiVersion: v1
kind: Route
metadata:
  labels:
    docker-registry: default
  name: docker-registry
spec:
  host: hub.10.2.2.2.xip.io
  port:
    targetPort: 5000-tcp
  tls:
    termination: edge
  to:
    kind: Service
    name: docker-registry
